name = "MicroVisualisations"
uuid = "917c7318-673f-4690-bceb-ddd865398252"
version = "1.0.0-DEV"
authors = ["Graham Stark"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BudgetConstraints = "51aacf4b-43e8-45f9-b960-ce5126c2a956"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PovertyAndInequalityMeasures = "582645c0-90fa-497a-98b9-936b80116c29"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ScottishTaxBenefitModel = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[sources]
ScottishTaxBenefitModel = {rev = "master", url = "https://github.com/grahamstark/ScottishTaxBenefitModel.jl"}

[compat]
ArgCheck = "2,3"
BudgetConstraints = "1"
CSV = "0,1"
CairoMakie = "0,1"
Colors = "0,1"
DataFrames = "1,2"
Dates = "1.11.0"
Documenter = "1.17.0"
Format = "1,2"
HypertextLiteral = "0.9,1"
Images = "0,1"
Makie = "0, 1"
Markdown = "1,2"
Observables = "0.5, 0.6, 1"
PovertyAndInequalityMeasures = "1"
Preferences = "1,2"
PrettyTables = "2,3"
ScottishTaxBenefitModel = "0,1"
StatsBase = "0,1"
UUIDs = "1,2"
ZipFile = "0.10.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.ScottishTaxBenefitModel]
aa_payment_rate = 1.0
ccode = ""
civil_payment_rate = 1.0
default_run_name = "sb-0.1.7"
do_indirect_tax_calculations = false
do_legal_aid = false
do_local_run = false
do_marginal_rates = true
do_replacement_rates = false
do_sfc_behavioural_changes = true
dump_frames = false
include_institutional_population = false
included_data_years = [2019, 2021, 2022, 2023]
indirect_method = "matching"
ineq_income_measure = "eq_bhc_net_income"
legal_aid_costs_strategy = "la_individual_costs"
legal_aid_probs_data = "civil-legal-aid-probs-scotland-map_to_slab"
local-artifact_server_upload_unix = "/mnt/data/ScotBen/local_artifacts/"
local-artifact_server_upload_windows = "/mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_unix = "file:///mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_windows = "file:///c:/data/"
lower_multiple = 0.6
means_tested_routing = "uc_full"
poverty_line_source = "pl_first_sys"
public-artifact_server_upload = "vw@virtual-worlds.biz:public_html/artifacts/"
public-artifact_server_url = "https://virtual-worlds.biz/artifacts/"
replacement_rate_hours = 30
target_nation = "N_Scotland"
to_q = 1
to_y = 2026
upper_multiple = 6
use_shs = true
wealth_method = "matching"
weighting_relative_to_ons_weights = false
weighting_strategy = "use_runtime_computed_weights"
weighting_target_year = 2026

[targets]
test = ["Test"]
